using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;

namespace EFCore.MultiTenant;

[Generator]
public sealed class MultiTenantGenerator : IIncrementalGenerator
{
    // ── Core infrastructure emitted into every consuming project ─────────────
    private const string CoreSource = @"// <auto-generated by Swevo.EFCore.MultiTenant/>
#nullable enable
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Diagnostics;

namespace EFCore.MultiTenant
{
    /// <summary>Marks an EF Core entity as tenant-scoped. Apply to a partial class.</summary>
    [AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
    public sealed class TenantAttribute : Attribute { }

    /// <summary>Provides the current tenant identifier for the executing context (e.g. per HTTP request).</summary>
    public interface ITenantContext
    {
        string TenantId { get; }
    }

    /// <summary>Implemented by every class decorated with [Tenant].</summary>
    public interface ITenantEntity
    {
        string TenantId { get; set; }
    }

    /// <summary>
    /// EF Core SaveChangesInterceptor that stamps TenantId on every new ITenantEntity
    /// before the INSERT is issued. Register via AddTenantInterceptor().
    /// </summary>
    public sealed class TenantInterceptor : SaveChangesInterceptor
    {
        private readonly ITenantContext _tenantContext;

        public TenantInterceptor(ITenantContext tenantContext) => _tenantContext = tenantContext;

        public override InterceptionResult<int> SavingChanges(
            DbContextEventData eventData,
            InterceptionResult<int> result)
        {
            StampTenantIds(eventData.Context);
            return result;
        }

        public override ValueTask<InterceptionResult<int>> SavingChangesAsync(
            DbContextEventData eventData,
            InterceptionResult<int> result,
            CancellationToken cancellationToken = default)
        {
            StampTenantIds(eventData.Context);
            return base.SavingChangesAsync(eventData, result, cancellationToken);
        }

        private void StampTenantIds(DbContext? context)
        {
            if (context is null) return;
            foreach (var entry in context.ChangeTracker.Entries<ITenantEntity>())
                if (entry.State == EntityState.Added)
                    entry.Entity.TenantId = _tenantContext.TenantId;
        }
    }

    public static class TenantInterceptorExtensions
    {
        /// <summary>
        /// Registers a TenantInterceptor that stamps TenantId on new rows.
        /// Call this inside AddDbContext / OnConfiguring.
        /// </summary>
        public static DbContextOptionsBuilder AddTenantInterceptor(
            this DbContextOptionsBuilder optionsBuilder,
            ITenantContext tenantContext)
        {
            optionsBuilder.AddInterceptors(new TenantInterceptor(tenantContext));
            return optionsBuilder;
        }
    }

    public static class TenantModelBuilderExtensions
    {
        /// <summary>
        /// Adds a global EF Core query filter to every ITenantEntity so queries
        /// automatically return only rows belonging to the current tenant.
        /// Call this inside OnModelCreating.
        /// </summary>
        public static ModelBuilder AddTenantQueryFilters(
            this ModelBuilder modelBuilder,
            ITenantContext tenantContext)
        {
            foreach (var entityType in modelBuilder.Model.GetEntityTypes())
            {
                if (!typeof(ITenantEntity).IsAssignableFrom(entityType.ClrType))
                    continue;

                var param        = Expression.Parameter(entityType.ClrType, ""e"");
                var tenantIdProp = Expression.Property(param, nameof(ITenantEntity.TenantId));
                var tenantIdVal  = Expression.Property(
                    Expression.Constant(tenantContext),
                    nameof(ITenantContext.TenantId));
                var body   = Expression.Equal(tenantIdProp, tenantIdVal);
                var filter = Expression.Lambda(body, param);

                entityType.SetQueryFilter(filter);
            }

            return modelBuilder;
        }
    }
}
";

    // ── Diagnostics ──────────────────────────────────────────────────────────
    private static readonly DiagnosticDescriptor MTNT001 = new DiagnosticDescriptor(
        id: "MTNT001",
        title: "[Tenant] requires a partial class",
        messageFormat: "'{0}' has [Tenant] but is not declared as partial. Add the 'partial' modifier to enable TenantId generation.",
        category: "EFCore.MultiTenant",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    // ── Data model ───────────────────────────────────────────────────────────
    private sealed class TenantModel
    {
        public string TypeName  { get; set; } = "";
        public string Namespace { get; set; } = "";
        public bool   IsPartial { get; set; }
    }

    // ── Initialize ───────────────────────────────────────────────────────────
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
            ctx.AddSource("EFCore.MultiTenant.Core.g.cs", CoreSource));

        var entities = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "EFCore.MultiTenant.TenantAttribute",
                predicate: static (n, _) => n is ClassDeclarationSyntax,
                transform: Transform)
            .Where(static x => x is not null)
            .Select(static (x, _) => x!);

        context.RegisterSourceOutput(entities, Generate);
    }

    // ── Transform ────────────────────────────────────────────────────────────
    private static TenantModel? Transform(GeneratorAttributeSyntaxContext ctx, CancellationToken ct)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol type) return null;

        var decl      = (ClassDeclarationSyntax)ctx.TargetNode;
        bool isPartial = decl.Modifiers.Any(SyntaxKind.PartialKeyword);

        var ns = type.ContainingNamespace is { IsGlobalNamespace: false } n
            ? n.ToDisplayString()
            : string.Empty;

        return new TenantModel
        {
            TypeName  = type.Name,
            Namespace = ns,
            IsPartial = isPartial
        };
    }

    // ── Code generation ──────────────────────────────────────────────────────
    private static void Generate(SourceProductionContext ctx, TenantModel model)
    {
        if (!model.IsPartial)
        {
            ctx.ReportDiagnostic(Diagnostic.Create(MTNT001, Location.None, model.TypeName));
            return;
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated by Swevo.EFCore.MultiTenant/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        bool hasNs = !string.IsNullOrEmpty(model.Namespace);
        if (hasNs)
        {
            sb.AppendLine($"namespace {model.Namespace}");
            sb.AppendLine("{");
        }

        sb.AppendLine($"    public partial class {model.TypeName} : global::EFCore.MultiTenant.ITenantEntity");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <summary>Identifies which tenant owns this row. Set automatically by TenantInterceptor on insert.</summary>");
        sb.AppendLine("        public string TenantId { get; set; } = string.Empty;");
        sb.AppendLine("    }");

        if (hasNs) sb.AppendLine("}");

        ctx.AddSource($"EFCore.MultiTenant.{model.TypeName}.g.cs", sb.ToString());
    }
}
